server:
  port: 8080


employee-data-service:
  paths:
    camelURICheckExist: http://127.0.0.1:8090/employee-data/exist?throwExceptionOnFailure=false
    camelURICreateNew: http://127.0.0.1:8090/employee-data?throwExceptionOnFailure=false